src/main/java/square2/modules/model/admin/UserBean.java
package square2.modules.model.admin;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * @author henkej
 * 
 */
public class UserBean implements Serializable, Comparable<UserBean> {
	private static final long serialVersionUID = 1L;
	private String forename;
	private String surname;
	private String username;
	private Integer usnr;
	private Date expire;

	public String toString() {
		StringBuilder buf = new StringBuilder();
		buf.append(forename).append(" ").append(surname);
		buf.append(" (").append(username).append(", ");
		buf.append(usnr).append(")");
		buf.append(expire);
		return buf.toString();
	}

	@Override
	public int compareTo(UserBean o) {
		String sortname = getSortname();
		return o == null ? 0 : sortname.compareTo(o.getSortname());
	}

	/**
	 * @return true if expire is before the current date
	 */
	public Boolean getIsExpired() {
		return expire == null ? null : expire.before(new Date());
	}

	private String getSortname() {
		return new StringBuilder().append(surname).append(forename).toString().toLowerCase();
	}

	/**
	 * get the full name of the user
	 * 
	 * @return the full name
	 */
	public String getFullname() {
		return new StringBuilder().append(forename).append(" ").append(surname).toString();
	}

	/**
	 * @return the forename
	 */
	public String getForename() {
		return forename;
	}

	/**
	 * @param forename
	 *          the forename to set
	 */
	public void setForename(String forename) {
		this.forename = forename;
	}

	/**
	 * @return the surname
	 */
	public String getSurname() {
		return surname;
	}

	/**
	 * @param surname
	 *          the surname to set
	 */
	public void setSurname(String surname) {
		this.surname = surname;
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username
	 *          the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the usnr
	 */
	public Integer getUsnr() {
		return usnr;
	}

	/**
	 * @param usnr
	 *          the usnr to set
	 */
	public void setUsnr(Integer usnr) {
		this.usnr = usnr;
	}

	/**
	 * @return the expire
	 */
	public Date getExpire() {
		return expire;
	}

	/**
	 * @param expire
	 *          the expire to set
	 */
	public void setExpire(Date expire) {
		this.expire = expire;
	}
}

src/main/java/square2/modules/model/cohort/CohortStudyBean.java
package square2.modules.model.cohort;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.jooq.JSONB;

import de.ship.dbppsquare.square.enums.EnumAccesslevel;

/**
 * 
 * @author henkej
 *
 */
public class CohortStudyBean implements Serializable, Comparable<CohortStudyBean> {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer parentId;
	private String name;
	private String uniqueName;
	private String parentName;
	private JSONB translation;
	private JSONB locales;
	private Date startDate;
	private Date designfeature;
	private Integer participants;
	private Integer right;
	private EnumAccesslevel acl;
	private final List<StudyAttributeBean> attributes;
	private final List<StudyAttributeBean> availableAttributes;

	/**
	 * create a new study cohort bean with an empty list of attributes
	 * 
	 * @param availableAttributes lists all available attributes
	 * @param locales the available locales for this study
	 */
	public CohortStudyBean(final List<StudyAttributeBean> availableAttributes, JSONB locales) {
		this.attributes = new ArrayList<>();
		this.availableAttributes = availableAttributes;
	}

	@Override
	public int compareTo(CohortStudyBean bean) {
		return bean == null || bean.getUniqueName() == null ? 0 : bean.getUniqueName().compareTo(uniqueName);
	}

	/**
	 * add the attribute of availableAttributes referenced by key
	 * 
	 * @param key the key
	 */
	public void addAttribute(String key) {
		for (StudyAttributeBean bean : availableAttributes) {
			if (bean.getKey().equals(key) && !attributes.contains(bean)) {
				attributes.add(bean);
			}
		}
	}

	/**
	 * @return the missing attributes
	 */
	public List<StudyAttributeBean> getMissingAttributes() {
		List<StudyAttributeBean> missingAttrs = new ArrayList<>();
		for (StudyAttributeBean bean : availableAttributes) {
			if (!attributes.contains(bean)) {
				missingAttrs.add(bean);
			}
		}
		return missingAttrs;
	}

	/**
	 * @return true if acl contains write = true, false otherwise
	 */
	public boolean getCanWrite() {
		return acl == null ? false : acl.getLiteral().contains("w");
	}

	/**
	 * @return true if acl contains execute = true, false otherwise
	 */
	public boolean getCanUse() {
		return acl == null ? false : acl.getLiteral().contains("x");
	}
	
	/**
	 * get the locales json string
	 * 
	 * @return the json string of the locales
	 */
	public String getLocalesJson() {
		return locales == null ? "{}" : locales.data();
	}
	
	/**
	 * get the json string of the translation
	 * 
 	 * @return the json string
	 */
	public String getTranslationJson() {
		return translation == null ? "{}" : translation.data();
	}
	
	/**
	 * set the json string
	 * 
	 * @param json the json string
	 */
	public void setTranslationJson(String json) {
		translation = json == null ? JSONB.valueOf("{}") : JSONB.valueOf(json);
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the parentId
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * @param parentId the parentId to set
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the translation
	 */
	public JSONB getTranslation() {
		return translation;
	}

	/**
	 * @param translation the translation to set
	 */
	public void setTranslation(JSONB translation) {
		this.translation = translation;
	}

	/**
	 * @return the startDate
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * @param startDate the startDate to set
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * @return the designfeature
	 */
	public Date getDesignfeature() {
		return designfeature;
	}

	/**
	 * @param designfeature the designfeature to set
	 */
	public void setDesignfeature(Date designfeature) {
		this.designfeature = designfeature;
	}

	/**
	 * @return the participants
	 */
	public Integer getParticipants() {
		return participants;
	}

	/**
	 * @param participants the participants to set
	 */
	public void setParticipants(Integer participants) {
		this.participants = participants;
	}

	/**
	 * @return the right
	 */
	public Integer getRight() {
		return right;
	}

	/**
	 * @param right the right to set
	 */
	public void setRight(Integer right) {
		this.right = right;
	}

	/**
	 * @return the acl
	 */
	public EnumAccesslevel getAcl() {
		return acl;
	}

	/**
	 * @param acl the acl to set
	 */
	public void setAcl(EnumAccesslevel acl) {
		this.acl = acl;
	}

	/**
	 * @return the unique name
	 */
	public String getUniqueName() {
		return uniqueName;
	}

	/**
	 * @param uniqueName the unique name to set
	 */
	public void setUniqueName(String uniqueName) {
		this.uniqueName = uniqueName;
	}

	/**
	 * @return the attributes
	 */
	public List<StudyAttributeBean> getAttributes() {
		return attributes;
	}

	/**
	 * @return the availableAttributes
	 */
	public List<StudyAttributeBean> getAvailableAttributes() {
		return availableAttributes;
	}

	/**
	 * @return the parentName
	 */
	public String getParentName() {
		return parentName;
	}

	/**
	 * @param parentName the parentName to set
	 */
	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	/**
	 * @return the locales
	 */
	public JSONB getLocales() {
		return locales;
	}
	
	/**
	 * @param locales the locales to set
	 */
	public void setLocales(JSONB locales) {
		this.locales = locales;
	}
}

src/main/java/square2/modules/model/cohort/StudyAttributeBean.java
package square2.modules.model.cohort;

import java.io.Serializable;

import org.jooq.JSONB;

/**
 * 
 * @author henkej
 *
 */
public class StudyAttributeBean implements Serializable, Comparable<StudyAttributeBean> {
	private static final long serialVersionUID = 1L;

	private final String key;
	private final String inputtype;
	private final JSONB typerestriction;
	private JSONB value;
	
	/**
	 * create a new study attribute bean
	 * 
	 * @param key the key of the attribute
	 * @param inputtype the name of the input type
	 * @param typerestriction the type restriction
	 */
	public StudyAttributeBean(String key, String inputtype, JSONB typerestriction) {
		this.key = key;
		this.inputtype = inputtype;
		this.typerestriction = typerestriction;
	}
	
	@Override
	public int compareTo(StudyAttributeBean bean) {
		return bean == null || bean.getKey() == null ? 0 : bean.getKey().compareTo(key);
	}
	
	@Override
	public boolean equals(Object o) {
		return (o instanceof StudyAttributeBean) && ((StudyAttributeBean) o).getKey().equals(key);
	}

	/**
	 * @return the json representation of the value
	 */
	public String getJsonValue() {
		return value == null ? null : value.data();
	}
	
	/**
	 * @param value the value to be set
	 */
	public void setJsonValue(String value) {
		this.value = value == null ? null : JSONB.jsonb(value);
	}
	
	/**
	 * @return the json representation of the type restriction
	 */
	public String getJsonTyperestriction() {
		return typerestriction == null ? null : typerestriction.data();
	}
	
	/**
	 * @return the value
	 */
	public JSONB getValue() {
		return value;
	}

	/**
	 * @param value the value to set
	 */
	public void setValue(JSONB value) {
		this.value = value;
	}

	/**
	 * @return the key
	 */
	public String getKey() {
		return key;
	}

	/**
	 * @return the inputtype
	 */
	public String getInputtype() {
		return inputtype;
	}

	/**
	 * @return the typerestriction
	 */
	public JSONB getTyperestriction() {
		return typerestriction;
	}
}

src/main/java/square2/modules/control/CohortController.java
package square2.modules.control;

import java.util.Map;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import square2.modules.control.help.Pages;
import square2.modules.model.AclBean;
import square2.modules.model.cohort.CohortModel;
import square2.modules.model.cohort.CohortStudyBean;
import square2.modules.model.cohort.StudygroupBean;

/**
 * 
 * @author henkej
 *
 */
@Named
@RequestScoped
public class CohortController extends SubmenuController {
	private static final Logger LOGGER = LogManager.getLogger(CohortController.class);

	@Inject
	@Named(value = "cohortModel")
	private CohortModel model;

	/**
	 * create a cohort controller
	 */
	public CohortController() {
		super(Pages.COHORT_ADD, Pages.COHORT_EDIT, Pages.COHORT_USER, Pages.COHORT_WELCOME,
				Pages.COHORT_LISTSTUDYGROUP, Pages.COHORT_ADDSTUDYGROUP, Pages.COHORT_EDITSTUDYGROUP);
	}

	/**
	 * navigate to welcome page
	 * 
	 * @return navigation destination
	 */
	public String toWelcome() {
		forceRefresh();
		model.toWelcome(getFacesContext());
		return navigateTo(getFacesContext(), Pages.COHORT_WELCOME);
	}

	/**
	 * navigate to study group list page
	 * 
	 * @return navigation destination
	 */
	public String toListStudygroup() {
		model.toListStudygroup(getFacesContext());
		return navigateTo(getFacesContext(), Pages.COHORT_LISTSTUDYGROUP);
	}

	/**
	 * naviate to add page
	 * 
	 * @return navigation destination
	 */
	public String toAddStudy() {
		model.toAddStudy(getFacesContext());
		return navigateTo(getFacesContext(), Pages.COHORT_ADD);
	}

	/**
	 * naviate to add study group page
	 * 
	 * @return navigation destination
	 */
	public String toAddStudygroup() {
		model.toAddStudygroup(getFacesContext());
		return navigateTo(getFacesContext(), Pages.COHORT_ADDSTUDYGROUP);
	}

	/**
	 * navigate to item page
	 * 
	 * @param s
	 *          the cohort study bean
	 * @return navigation destination
	 */
	public String toUser(CohortStudyBean s) {
		model.toItem(getFacesContext(), s);
		return navigateTo(getFacesContext(), Pages.COHORT_USER);
	}

	/**
	 * @param s
	 *          the cohort study bean
	 */
	public void doShow(CohortStudyBean s) {
		model.toItem(getFacesContext(), s);
	}

	/**
	 * @param s
	 *          the cohort study bean
	 * @return navigation destination
	 */
	public String toEdit(CohortStudyBean s) {
		model.toItem(getFacesContext(), s);
		return navigateTo(getFacesContext(), Pages.COHORT_EDIT);
	}

	/**
	 * @param s
	 *          the study group bean
	 * @return navigation destination
	 */
	public String toEditStudygroup(StudygroupBean s) {
		model.toEditStudygroup(getFacesContext(), s);
		return navigateTo(getFacesContext(), Pages.COHORT_EDITSTUDYGROUP);
	}

	/**
	 * add a study
	 * 
	 * @return navigation destination
	 */
	public String doAddStudy() {
		boolean result = model.doAddStudy(getFacesContext());
		return result ? toWelcome() : navigateTo(getFacesContext(), Pages.COHORT_ADD);
	}

	/**
	 * add a study group
	 * 
	 * @return navigation destination
	 */
	public String doAddStudygroup() {
		boolean result = model.doAddStudygroup(getFacesContext());
		return result ? toListStudygroup() : navigateTo(getFacesContext(), Pages.COHORT_ADDSTUDYGROUP);
	}

	/**
	 * update a study
	 * 
	 * @return navigation destination
	 */
	public String doUpdateStudy() {
		boolean result = model.updateStudy(getFacesContext());
		return result ? toWelcome() : navigateTo(getFacesContext(), Pages.COHORT_EDIT);
	}

	/**
	 * update a study group
	 * 
	 * @return navigation destination
	 */
	public String doUpdateStudygroup() {
		boolean result = model.doUpdateStudygroup(getFacesContext());
		return result ? navigateTo(getFacesContext(), Pages.COHORT_LISTSTUDYGROUP)
				: navigateTo(getFacesContext(), Pages.COHORT_EDITSTUDYGROUP);
	}

	/**
	 * remove a study
	 * 
	 * @param bean
	 *          the bean to be removed
	 * 
	 * @return navigation destination
	 */
	public String doRemoveStudy(CohortStudyBean bean) {
		model.removeDataCollection(getFacesContext(), bean);
		forceRefresh();
		return toWelcome();
	}

	/**
	 * delete a study group and all of its children
	 * 
	 * @param bean
	 *          the study group
	 * @return navigation destination
	 */
	public String doRemoveStudygroup(StudygroupBean bean) {
		model.removeStudygroup(getFacesContext(), bean);
		return toListStudygroup();
	}

	/**
	 * add a privilege for that study
	 * 
	 * @return navigation destination
	 */
	public String doAddPrivilege() {
		model.addPrivilege(getFacesContext());
		forceRefresh();
		return toUser(model.getStudy());
	}

	/**
	 * remove a privilege from that study
	 * 
	 * @return navigation destination
	 */
	public String doDeletePrivilege() {
		model.deletePrivilege(getFacesContext());
		return toUser(model.getStudy());
	}

	/**
	 * change a privilege on that study
	 * 
	 * @return navigation destination
	 */
	public String doEditPrivilege() {
		model.editPrivilege(getFacesContext());
		return toUser(model.getStudy());
	}
	
	/**
	 * add attribute to study
	 */
	public void doAddAttribute() {
		model.addAttribute(getFacesContext());
	}

	/**
	 * remove attribute from study
	 * 
	 * @param key the id of the entry
	 */
	public void doRemoveAttribute(String key) {
		model.removeAttribute(getFacesContext(), key);
	}

	@Override
	public Map<Integer, Map<Integer, AclBean>> refreshMap() {
		try {
			return model.getRightMap(getFacesContext());
		} catch (Exception e) {
			getFacesContext().notifyException(e);
			LOGGER.error(e.getMessage(), e);
		}
		return null;
	}

  /**
   * @return true if the cancel button was hit
   */
  public boolean getCancelling() {
    return FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().containsKey("form:btn_cancel");
  }

	public boolean getIsCurrentController() {
		return getIsCurrentController(getFacesContext());
	}

	@Override
	public boolean getIsCurrentSubController() {
		return getIsCurrentSubController(getFacesContext());
	}
}

src/main/webapp/pages/cohort/edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
  xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship" xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
  <ui:composition template="/pages/primodaltemplate.xhtml">
    <ui:define name="title">
      <h:outputText value="#{facesContext.translate('title.cohort.edit', cohortModel.study.name)}" />
    </ui:define>
    <ui:define name="body">
      <p:panelGrid columns="2" style="width: 100%">
        <h:outputText value="#{facesContext.translate('label.study.parent')}" />
        <p:selectOneMenu id="parent_id" value="#{cohortModel.study.parentId}" filter="true" filterMatchMode="startsWith" valueChangeListener="#{cohortModel.updateLocales}" required="true"
          requiredMessage="#{facesContext.translate('error.mustnotbeempty', 'label.study.parent')}">
          <f:selectItem itemValue="" itemLabel="#{facesContext.translate('button.choose')}" />
          <f:selectItems value="#{cohortModel.studygroups}" var="p" itemValue="#{p.pk}" itemLabel="#{p.name}" />
          <p:ajax update="@form" onstart="ship.processing(10000)" oncomplete="ship.processed()" />
        </p:selectOneMenu>
        <h:outputText value="#{facesContext.translate('label.study.name')}" />
        <p:inputText id="name" value="#{cohortModel.study.name}" required="true" requiredMessage="#{facesContext.translate('error.mustnotbeempty', 'label.study.name')}">
          <f:attribute name="allowed" value="#{cohortModel.study.name}" />
          <f:validator validatorId="square.modules.model.cohort.StudyNameValidator" />
          <p:ajax update="@form" onstart="ship.processing(10000)" oncomplete="ship.processed()" />
        </p:inputText>
        <h:outputText value="#{facesContext.translate('label.study.description')}" />
        <ship:inputJson id="description" value="#{cohortModel.study.translationJson}" required="true" type="translation" typerestriction="#{cohortModel.study.localesJson}"
          labelall="#{facesContext.translate('label.display.all.translations')}" requiredMessage="#{facesContext.translate('error.mustnotbeempty', 'label.study.description')}" />
        <h:outputText value="#{facesContext.translate('label.study.startdate')}" />
        <p:datePicker id="startdt" value="#{cohortModel.study.startDate}" showTime="false" pattern="dd.MM.yyyy" />
        <h:outputText value="#{facesContext.translate('label.study.designfeature')}" />
        <p:datePicker id="designfeature" value="#{cohortModel.study.designfeature}" showTime="false" pattern="dd.MM.yyyy" />
        <h:outputText value="#{facesContext.translate('label.study.participants')}" />
        <p:inputNumber id="participants" value="#{cohortModel.study.participants}" decimalPlaces="0" />
        <h:outputText value="#{facesContext.translate('label.study.uniquename')}" />
        <h:outputText value="#{cohortModel.study.uniqueName}" />
      </p:panelGrid>
      <p:panelGrid id="studyattr" columns="2" rendered="#{!cohortModel.study.missingAttributes.isEmpty()}">
        <p:dataTable value="#{cohortModel.study.attributes}" var="sa">
          <p:column>
            <h:outputText value="#{sa.key}" />
            <f:facet name="footer">
              <p:selectOneMenu value="#{cohortModel.newAttributeKey}">
                <f:selectItems value="#{cohortModel.study.missingAttributes}" var="ma" itemValue="#{ma.key}" itemLabel="#{ma.key}" />
              </p:selectOneMenu>
            </f:facet>
          </p:column>
          <p:column>
            <ship:inputJson value="#{sa.jsonValue}" inputtype="#{sa.inputtype}" typerestriction="#{sa.jsonTyperestriction}" />
            <f:facet name="footer">
              <p:commandButton action="#{cohortController.doAddAttribute}" value="#{facesContext.translate('button.add')}" update="form:studyattr" />
            </f:facet>
          </p:column>
          <p:column>
            <p:commandButton action="#{cohortController.doRemoveAttribute(sa.key)}" value="#{facesContext.translate('button.remove')}" update="form:studyattr" />
          </p:column>
        </p:dataTable>
      </p:panelGrid>
    </ui:define>
    <ui:define name="formbuttons">
      <p:commandButton id="btn_ok" action="#{cohortController.doUpdateStudy}" value="#{facesContext.translate('button.approve')}" ajax="false" />
      <p:commandButton id="btn_cancel" action="#{cohortController.toWelcome}" value="#{facesContext.translate('button.cancel')}" ajax="false" immediate="true" />
    </ui:define>
    <ui:define name="help_de">
			Hier können Sie Attribute der Studie veränden. Um Ihre Änderungen zu speichern, klicken Sie bitte auf <i>Übernehmen</i>.<br />
      <br />
			Der Unique-Name ist nicht veränderbar, da er von Square² zur eindeutigen Identifikation automatisch zugewiesen wird.
		</ui:define>
    <ui:define name="help_en">
			Here you can edit certain attributes of the study. To save changes please click <i>approve</i>.<br />
      <br />
			Changing the unique name isn't possible. It's assigned automatically by Square² to enable an unambiguous identification.
		</ui:define>
    <ui:define name="help_ro">
		  Aici puteți modifica atributele studiului. Pentru a salva modificările, faceți clic pe <i>Preluare</i>.<br />
      <br />
		  Numele unic nu poate fi schimbat, deoarece este atribuit automat de Square² pentru o identificare unică.
		</ui:define>
  </ui:composition>
</h:body>
</html>

src/main/webapp/pages/cohort/show.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship" xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
	<ui:composition template="/pages/primodaltemplate.xhtml">
		<ui:define name="title">
			<h:outputText value="#{facesContext.translate('title.study.show', cohortModel.study.name)}" />
		</ui:define>
		<ui:define name="body">
			<p:panelGrid columns="2">
				<h:outputText value="#{facesContext.translate('label.study.parent')}" />
				<h:outputText value="#{cohortModel.study.parentName}" />
				<h:outputText value="#{facesContext.translate('label.study.name')}" />
				<h:outputText value="#{cohortModel.study.name}" />
				<h:outputText value="#{facesContext.translate('label.study.description')}" />
				<ship:outputTranslation value="#{cohortModel.study.translation}" />
				<h:outputText value="#{facesContext.translate('label.study.startdate')}" />
				<h:outputText value="#{cohortModel.study.startDate}">
					<f:convertDateTime pattern="dd.MM.yyyy" />
				</h:outputText>
				<h:outputText value="#{facesContext.translate('label.study.designfeature')}" />
				<h:outputText value="#{cohortModel.study.designfeature}">
					<f:convertDateTime pattern="dd.MM.yyyy" />
				</h:outputText>
				<h:outputText value="#{facesContext.translate('label.study.participants')}" />
				<h:outputText value="#{cohortModel.study.participants}" />
				<h:outputText value="#{facesContext.translate('label.study.uniquename')}" />
				<h:outputText value="#{cohortModel.study.uniqueName}" />
			</p:panelGrid>
			<p:dataTable value="#{cohortModel.study.attributes}" var="sa">
				<p:column>
					<h:outputText value="#{sa.key}" />
				</p:column>
				<p:column>
					<h:outputText value="#{sa.jsonValue}" />
				</p:column>
			</p:dataTable>
		</ui:define>
		<ui:define name="formbuttons">
			<p:commandButton id="btn_cancel" action="#{cohortController.toWelcome}" value="#{facesContext.translate('button.overview')}" />
			<p:commandButton id="btn_edit" action="#{cohortController.toEdit(cohortModel.study)}" value="#{facesContext.translate('button.edit')}" immediate="true" rendered="#{cohortModel.study.canWrite}" />
		</ui:define>
		<ui:define name="help_de">
			Hier sind alle Attribute der Studie <h:outputText value="#{cohortModel.study.name}" /> aufgelistet.<br />Über <i>Bearbeiten</i> können Sie diese verändern. 
		</ui:define>
		<ui:define name="help_en">
		  Here you find all attributes of the study <h:outputText value="#{cohortModel.study.name}" />.<br />You can change it via <i>edit</i>.
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/cohort/user.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship" xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
	<ui:composition template="/pages/primodaltemplate.xhtml">
		<ui:define name="title">
			<h:outputText value="#{facesContext.translate('title.item.user', cohortModel.study.name)}" />
		</ui:define>
		<ui:define name="body">
			<ship:priuserpanel actionAdd="#{cohortController.doAddPrivilege}" actionEdit="#{cohortController.doEditPrivilege}" actionDelete="#{cohortController.doDeletePrivilege}"
				activeElement="#{cohortModel.activePrivilege}" list="#{cohortModel.groupPrivileges}" allGroups="#{cohortModel.allGroups}" allUsers="#{cohortModel.allSquareUsers}"
				newGroup="#{cohortModel.newGroup}" newUser="#{cohortModel.newUsnr}" newAcl="#{cohortModel.newAcl}" renderRead="false" labelWrite="label.accesslevel.study.1"
				labelExecute="label.accesslevel.study.2" facesContext="#{facesContext}" rendered="#{cohortModel.study.canWrite}">
			</ship:priuserpanel>
		</ui:define>
		<ui:define name="formbuttons">
			<p:commandButton id="btn_cancel" action="#{cohortController.toWelcome}" ajax="false" value="#{facesContext.translate('button.overview')}" />
		</ui:define>
		<ui:define name="help_de">
			TODO StS: Steuern Sie hierüber die Rechte von Nutzern / Nutzergruppen an der eingestellten Studie.
		</ui:define>
	</ui:composition>
</h:body>
</html>