src/main/java/square2/db/control/model/EnumVarlist.java
package square2.db.control.model;

import org.jooq.exception.DataAccessException;

/**
 * 
 * @author henkej
 *
 */
public enum EnumVarlist {
	/**
	 * for true in the database
	 */
	TRUE(true, "true"),
	/**
	 * for false in the database
	 */
	FALSE(false, "false"),
	/**
	 * for null in the database
	 */
	NULL(null, "empty");

	private EnumVarlist(Boolean dbValue, String jsfValue) {
		this.dbValue = dbValue;
		this.jsfValue = jsfValue;
	}

	private final Boolean dbValue;
	private final String jsfValue;

	/**
	 * return enum from jsf value
	 * 
	 * @param value
	 *          value to be looked up
	 * @return the enum if found, null otherwise

	 *           if anything went wrong on database side
	 */
	public EnumVarlist fromJsf(String value) {
		if (value == null) {
			return EnumVarlist.NULL;
		} else if (value.trim().equals("")) {
			return EnumVarlist.NULL;
		} else if (EnumVarlist.NULL.getJsfValue().equals(value)) {
			return EnumVarlist.NULL;
		} else if (EnumVarlist.TRUE.jsfValue.equals(value)) {
			return EnumVarlist.TRUE;
		} else if (EnumVarlist.FALSE.jsfValue.equals(value)) {
			return EnumVarlist.FALSE;
		} else {
			throw new DataAccessException("no such enum found: " + value);
		}
	}

	/**
	 * return enum from db value
	 * 
	 * @param value
	 *          value to be looked up
	 * @return the enum if found, null otherwise
	 */
	public EnumVarlist fromDb(Boolean value) {
		if (value == null) {
			return EnumVarlist.NULL;
		} else if (value) {
			return EnumVarlist.TRUE;
		} else {
			return EnumVarlist.FALSE;
		}
	}

	/**
	 * @return the dbValue
	 */
	public Boolean getDbValue() {
		return dbValue;
	}

	/**
	 * @return the jsfValue
	 */
	public String getJsfValue() {
		return jsfValue;
	}
}

src/main/java/square2/db/control/model/LambdaResultWrapper.java
package square2.db.control.model;

/**
 * 
 * @author henkej
 *
 */
public class LambdaResultWrapper {
	private Integer integer;
	private String string;
	private Boolean bool;

	/**
	 * set the integer value
	 * 
	 * @param amount
	 *          the value
	 */
	public void setInteger(Integer amount) {
		this.integer = amount;
	}

	/**
	 * get the integer value
	 * 
	 * @return the value
	 */
	public Integer getInteger() {
		return integer;
	}

	/**
	 * get the string value
	 * 
	 * @return the value
	 */
	public String getString() {
		return string;
	}

	/**
	 * set the string value
	 * 
	 * @param string
	 *          the value
	 */
	public void setString(String string) {
		this.string = string;
	}

	/**
	 * add amount to the integer
	 * 
	 * @param amount
	 *          value to be added to the integer variable
	 */
	public void addToInteger(int amount) {
		this.integer = integer == null ? amount : integer + amount;
	}

	/**
	 * @return the bool
	 */
	public Boolean getBool() {
		return bool;
	}

	/**
	 * @param bool
	 *          the bool
	 */
	public void setBool(Boolean bool) {
		this.bool = bool;
	}
}

src/main/java/square2/db/control/model/TableColumnBean.java
package square2.db.control.model;

/**
 * 
 * @author henkej
 *
 */
public class TableColumnBean {
	private final String tableName;
	private final String columnName;
	private final String dataType;
	private final Integer rowcount;

	/**
	 * generate new table column bean
	 * 
	 * @param tableName
	 *          name of the table
	 * @param columnName
	 *          name of the column
	 * @param dataType
	 *          datatype of the column
	 * @param rowcount
	 *          the row count
	 */
	public TableColumnBean(String tableName, String columnName, String dataType, Integer rowcount) {
		this.tableName = tableName;
		this.columnName = columnName;
		this.dataType = dataType;
		this.rowcount = rowcount;
	}

	/**
	 * get the table name
	 * 
	 * @return table name
	 */
	public String getTableName() {
		return tableName;
	}

	/**
	 * get the column name
	 * 
	 * @return column name
	 */
	public String getColumnName() {
		return columnName;
	}

	/**
	 * get the data type
	 * 
	 * @return data type
	 */
	public String getDataType() {
		return dataType;
	}

	/**
	 * get the row count
	 * 
	 * @return the row count
	 */
	public Integer getRowcount() {
		return rowcount;
	}
}

src/main/java/square2/db/control/model/TranslationsBean.java
package square2.db.control.model;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * 
 * @author henkej
 *
 */
public class TranslationsBean {
	private Map<String, Map<String, String>> isocodes;

	/**
	 * generate a new translations bean
	 * 
	 * @param locales
	 *          set of all available locales
	 */
	public TranslationsBean(Set<String> locales) {
		isocodes = new HashMap<>();
		for (String locale : locales) {
			isocodes.put(locale, new HashMap<>());
		}
	}

	/**
	 * get complete map of isocode
	 * 
	 * @param isocode
	 *          code to be used
	 * @return map of translations for this isocode or null if isocode is not found
	 */
	public Map<String, String> get(String isocode) {
		return isocodes.get(isocode);
	}

}

src/main/java/square2/latex/model/LatexPatternSnippletType.java
package square2.latex.model;

/**
 * 
 * @author henkej
 *
 */
public class LatexPatternSnippletType implements SnippletTypeInterface {
	private final String code;
	private final String template;

	/**
	 * create new latex pattern snipplet type
	 * 
	 * @param code
	 *          the replacement for all <b>${code}</b> blocks in template
	 * @param template
	 *          the string that contains <b>${code}</b> to be replaced
	 */
	public LatexPatternSnippletType(String code, String template) {
		this.code = code;
		this.template = template;
	}

	@Override
	public String toLatex() {
		return template.replaceAll("${code}", code);
	}
}

src/main/java/square2/latex/model/SnippletTypeInterface.java
package square2.latex.model;

/**
 * 
 * @author henkej
 *
 */
public interface SnippletTypeInterface {
	/**
	 * generate complete latex snipplet
	 * 
	 * @return latex snipplet
	 */
	public String toLatex();
}

src/main/java/square2/modules/model/ApplicationBean.java
package square2.modules.model;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import square2.help.SquareFacesContext;
import square2.modules.model.admin.UserLoginBean;

/**
 * 
 * @author henkej
 *
 */
@Named(value = "applicationBean")
@ApplicationScoped
public class ApplicationBean {
	private List<UserLoginBean> userLogins;

	/**
	 * create new application bean
	 */
	public ApplicationBean() {
		userLogins = new ArrayList<>();
	}

	@Override
	public String toString() {
		StringBuilder buf = new StringBuilder(this.getClass().getSimpleName());
		buf.append("@{userLogins=").append(userLogins);
		buf.append("}");
		return buf.toString();
	}

	/**
	 * add profile
	 * 
	 * @param bean
	 *          the profile
	 * @param facesContext
	 *          the context of this function call
	 */
	public void addProfile(ProfileBean bean, SquareFacesContext facesContext) {
		Iterator<UserLoginBean> i = userLogins.iterator();
		while (i.hasNext()) {
			UserLoginBean uBean = i.next();
			if (uBean.getUsnr().equals(bean.getUsnr())) {
				facesContext.notifyWarning("warning.login.missing.logout",
						new SimpleDateFormat("dd.MM.yyyy, HH:mm").format(uBean.getStart()));
				i.remove();
			}
		}
		userLogins.add(new UserLoginBean(bean));
	}

	/**
	 * @return the profiles
	 */
	public List<UserLoginBean> getProfiles() {
		return userLogins;
	}

	/**
	 * remove profile from list
	 * 
	 * @param usnr
	 *          the id of the user
	 */
	public void removeProfile(Integer usnr) {
		Iterator<UserLoginBean> i = userLogins.iterator();
		while (i.hasNext()) {
			if (i.next().getUsnr().equals(usnr)) {
				i.remove();
				return;
			}
		}
	}
}

src/main/java/square2/modules/model/LocaleBean.java
package square2.modules.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Matcher;

import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIInput;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Named;
import javax.servlet.ServletContext;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import square2.help.ContextKey;
import square2.help.SquareFacesContext;

/**
 * 
 * @author henkej
 * 
 */
@Named(value = "lang")
@SessionScoped
public class LocaleBean implements Serializable {
	private static final Logger LOGGER = LogManager.getLogger(LocaleBean.class);

	private static final long serialVersionUID = -2920852271046380884L;

	private String localeCode;

	private static Map<String, Locale> countries;

	static {
		countries = new LinkedHashMap<>();
		countries.put("English", Locale.ENGLISH);
		countries.put("German", Locale.GERMANY);
		countries.put("Romanian", Locale.forLanguageTag("ro"));
		countries.put("Spanish", Locale.forLanguageTag("es"));
		countries.put("languagekey", Locale.CHINA); // use valid languages
	}

	/**
	 * generate new locale bean with default locale de_DE
	 */
	public LocaleBean() {
		super();
		localeCode = "de_DE"; // defaults to german
	}

	/**
	 * @param localeCode
	 *          the default locale code, e.g. de_DE
	 */
	public LocaleBean(String localeCode) {
		super();
		this.localeCode = localeCode;
	}

	@Override
	public String toString() {
		StringBuilder buf = new StringBuilder(this.getClass().getSimpleName());
		buf.append("@{localeCode=").append(localeCode);
		buf.append(",countries=").append(countries);
		buf.append("}");
		return buf.toString();
	}

	/**
	 * replace params and translate key
	 * 
	 * @param facesContext
	 *          the context of this function call
	 * @param key
	 *          the key of the translation
	 * @param params
	 *          the parameters for that translation
	 * @return the translation if possible, the key otherwise
	 */
	public String translateParametrized(FacesContext facesContext, String key, Object... params) {
		int i = 0;
		if (key != null) {
			for (Object o : params) {
				if (o != null) {
					key = key.replaceAll("\\{" + i + "\\}",
							Matcher.quoteReplacement(translate(facesContext, null, o.toString())));
				}
				i++;
			}
		}
		return translate(facesContext, null, key);
	}

	/**
	 * translate key and replace params
	 * 
	 * @param facesContext
	 *          the context of this function call
	 * @param key
	 *          the key of the translation
	 * @param params
	 *          the parameters for that translation
	 * @return the translation if possible, the key otherwise
	 */
	public String translate(FacesContext facesContext, Integer key, Object... params) {
		return translate(facesContext, key, null, params);
	}

	/**
	 * translate key and replace params
	 * 
	 * @param facesContext
	 *          the context of this function call
	 * @param key
	 *          the numerical key of the translation
	 * @param name
	 *          the string key of the translation
	 * @param params
	 *          the parameters for that translation
	 * @return the translation if possible, the key otherwise
	 */
	public String translate(FacesContext facesContext, Integer key, String name, Object... params) {
		String translated = translate(facesContext, key, name);
		int i = 0;
		if (translated != null) {
			for (Object o : params) {
				if (o != null) {
					translated = translated.replaceAll("\\{" + i + "\\}",
							Matcher.quoteReplacement(translate(facesContext, null, o.toString())));
				}
				i++;
			}
		}
		return translated;
	}

	/**
	 * translate key
	 * 
	 * @param facesContext
	 *          the context of this function call
	 * @param key
	 *          the key of the translation
	 * @param params
	 *          the parameters for that translation
	 * @return the translation if possible, the key otherwise
	 */
	public String translate(FacesContext facesContext, String key, Object... params) {
		return translate(facesContext, null, key, params);
	}

	/**
	 * translate key; if no translation is found (in current locale), return the key
	 * itself
	 * 
	 * @param facesContext
	 *          the context of this function call
	 * @param key
	 *          the numerical key of the translation
	 * @param name
	 *          the string key of the translation
	 * @return the translation if possible, the key otherwise
	 */
	public String translate(FacesContext facesContext, Integer key, String name) {
		Map<String, String> p = null;
		String k = LangKey.generateKey(key, name);
		if (facesContext == null) {
			LOGGER.warn("facesContext is null in translate(facesContext, '{}')", k);
		} else {
			ExternalContext externalContext = facesContext.getExternalContext();
			if (externalContext == null) {
				LOGGER.warn("externalContext is null in translate(facesContext, '{}')", k);
			} else {
				ServletContext servletContext = (ServletContext) externalContext.getContext();
				if (servletContext == null) {
					LOGGER.warn("servletContext is null in translate(facesContext, '{}')", k);
				} else {
					LangBean bean = (LangBean) servletContext.getAttribute(ContextKey.TRANSLATIONS.get());
					Map<String, Map<String, String>> map = bean.getMap();
					if (map == null) {
						LOGGER.warn("attributeMap is null in translate(facesContext, '{}')", k);
					} else {
						p = map.get(localeCode);
					}
				}
			}
		}
		if (p == null) {
			LOGGER.error("locale " + localeCode + " is not supported");
			return k.toString();
		} else {
			return LocaleBean.getTranslation(p, key, name);
		}
	}

	/**
	 * @return the countries list
	 */
	public List<Locale> getCountries() {
		return new ArrayList<>(getCountriesInMap().values());
	}

	/**
	 * @return the countries map
	 */
	public Map<String, Locale> getCountriesInMap() {
		return countries;
	}

	/**
	 * @return the locale code, e.g. de_DE
	 */
	public String getLocaleCode() {
		return localeCode;
	}

	/**
	 * @return the simple locale code, e.g. de
	 */
	public String getSimpleLocaleCode() {
		return localeCode == null ? null
				: (localeCode.contains("_") ? localeCode.substring(0, localeCode.indexOf("_")) : localeCode);
	}

	/**
	 * @param localeCode
	 *          the locale code, e.g. de_DE
	 */
	public void setLocaleCode(String localeCode) {
		this.localeCode = localeCode;
	}

	/**
	 * set locale code and update view root
	 * 
	 * @param facesContext
	 *          the context of this function call
	 * @param localeCode
	 *          the new locale code
	 * @return the same page
	 */
	public String setLocaleCodeTo(SquareFacesContext facesContext, String localeCode) {
		setLocaleCode(localeCode);
		for (Map.Entry<String, Locale> entry : countries.entrySet()) {
			if (entry.getValue().toString().equals(localeCode)) {
				facesContext.getViewRoot().setLocale(entry.getValue());
				facesContext.setLocaleBean(this);
			}
		}
		return "";
	}

	/**
	 * switch the current locale
	 * 
	 * @param e
	 *          the value change event
	 */
	public void countryLocaleCodeChanged(ValueChangeEvent e) {
		SquareFacesContext facesContext = (SquareFacesContext) ((UIInput) e.getSource()).getAttributes()
				.get("facesContext");
		String newLocaleValue = e.getNewValue().toString();
		for (Map.Entry<String, Locale> entry : countries.entrySet()) {
			if (entry.getValue().toString().equals(newLocaleValue)) {
				facesContext.getViewRoot().setLocale(entry.getValue());
				facesContext.setLocaleBean(this);
			}
		}
	}

	/**
	 * get the translation of the element by name, ignoring the numerical key
	 * 
	 * @param facesContext
	 *          of this current function call
	 * @param name
	 *          to be used as key
	 * @param params
	 *          to be used in translation
	 * @return the translation if found, the name otherwise
	 */
	public String translateByName(SquareFacesContext facesContext, String name, Object... params) {
		Map<String, String> p = new HashMap<>();
		if (facesContext == null) {
			LOGGER.warn("facesContext is null in translate(facesContext, '{}')", name);
		} else {
			ExternalContext externalContext = facesContext.getExternalContext();
			if (externalContext == null) {
				LOGGER.warn("externalContext is null in translate(facesContext, '{}')", name);
			} else {
				ServletContext servletContext = (ServletContext) externalContext.getContext();
				if (servletContext == null) {
					LOGGER.warn("servletContext is null in translate(facesContext, '{}')", name);
				} else {
					LangBean bean = (LangBean) servletContext.getAttribute(ContextKey.TRANSLATIONS.get());
					if (bean == null) {
						LOGGER.warn("translation bean is null or not found in servlet context (key translations)");
					} else {
						Map<String, Map<String, String>> map = bean.getMap();
						if (map == null) {
							LOGGER.warn("translation map is null in translate(facesContext, '{}')", name);
						} else {
							p = map.get(localeCode);
						}
					}
				}
			}
		}
		return getTranslation(p, null, name);
	}

	/**
	 * get the translation of the element by name, ignoring the numerical key
	 * 
	 * !!! works only if t_languagekey.name is null !!!
	 * 
	 * @param facesContext
	 *          of this current function call
	 * @param key
	 *          to be used as key
	 * @param params
	 *          to be used in translation
	 * @return the translation if found, the name otherwise
	 */
	public String translateByKey(SquareFacesContext facesContext, Integer key, Object... params) {
		Map<String, String> p = new HashMap<>();
		if (facesContext == null) {
			LOGGER.warn("facesContext is null in translate(facesContext, '{}')", key);
		} else {
			ExternalContext externalContext = facesContext.getExternalContext();
			if (externalContext == null) {

src/main/webapp/pages/impressum.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship">
<h:head></h:head>
<h:body>
	<ui:composition template="/pages/pridiatemplate.xhtml">
		<ui:define name="location">
			<p:menubar rendered="#{profile == null}">
				<p:menuitem action="#{loginController.toLogin}" value="#{facesContext.translate('button.login')}" ajax="false" />
			</p:menubar>
		</ui:define>
		<ui:define name="loginbody">
			<p:panel header="#{facesContext.translate('title.impressum')}">
				<div id="impressum" class="textwithlinebreaks">
					<h:outputText value="#{facesContext.translate('label.square.impressum')}" />
				</div>
			</p:panel>
		</ui:define>
		<ui:define name="body">
			<p:panel header="#{facesContext.translate('title.impressum')}">
				<div id="impressum" class="textwithlinebreaks">
					<h:outputText value="#{facesContext.translate('label.square.impressum')}" />
				</div>
			</p:panel>
		</ui:define>
		<ui:define name="help_de">
    TODO: struckmanns
			Lesen Sie hier Informationen über den Betreiber der Webanwendung.
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</h:head>
<h:body>
	<ui:composition template="/pages/logintemplate.xhtml">
		<ui:define name="loginbody">
			<h:form id="form">
				<p:panel header="Login" style="width: 400px; margin-left: 33%; margin-top: 20%">
					<p:panelGrid columns="2" styleClass="borderlesspanelgrid">
						<h:outputLabel for="username" value="#{facesContext.translate('view.login.username')}" />
						<p:inputText id="username" label="username" value="#{loginModel.username}" required="true" requiredMessage="#{facesContext.translate('error.mustnotbeempty', 'view.login.username')}"
							placeholder="#{facesContext.translate('instruction.enter.username')}" />
						<h:outputLabel for="password" value="#{facesContext.translate('view.login.password')}" />
						<p:password id="password" label="password" value="#{loginModel.password}" required="true" requiredMessage="#{facesContext.translate('error.mustnotbeempty', 'view.login.password')}"
							placeholder="#{facesContext.translate('instruction.enter.password')}" />
					</p:panelGrid>
					<p:commandButton id="btn_login" action="#{loginController.doLogin}" ajax="false" value="#{facesContext.translate('view.login.login')}" />
				</p:panel>
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/main.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html">
<h:head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></h:head>
<h:body>
	<ui:composition template="/pages/pridiatemplate.xhtml">
		<ui:define name="help_de">
    TODO: struckmanns
			Hier soll erklärt werden, dass man sich im Hauptbereich befindet, ein Modul oben wählen kann und aktuell die installierten Bibliotheksversionen zu sehen sind.
			
			Ggf. gibt es hier auch noch Informationen über das Profil des Benutzers und, wie man dahin gelangen kann (Beschreibung der Menu-Buttons).
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/password.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship" xmlns:p="http://primefaces.org/ui" xmlns:c="http://java.sun.com/jsp/jstl/core">
<h:head></h:head>
<h:body>
	<ui:composition template="/pages/primodaltemplate.xhtml">
		<ui:define name="title">
			<h:outputText value="#{facesContext.translate('title.profile.password')}" />
		</ui:define>
		<ui:define name="body">
			<h:panelGrid columns="2" cellpadding="5">
				<h:outputLabel for="pwd1" value="#{facesContext.translate('view.profile.password')}" />
				<p:password id="pwd1" value="#{loginModel.password}" label="pwd1" required="true" requiredMessage="#{facesContext.translate('error.mustnotbeempty', 'view.profile.password')}"
					placeholder="#{facesContext.translate('instruction.enter.password')}" />
				<h:outputLabel for="pwd2" value="#{facesContext.translate('view.profile.password.again')}" />
				<p:password id="pwd2" value="#{loginModel.passwordAgain}" label="pwd2" required="true" requiredMessage="#{facesContext.translate('error.mustnotbeempty', 'view.profile.password.again')}"
					placeholder="#{facesContext.translate('instruction.enter.password.again')}" />
			</h:panelGrid>
			<ship:buttongroup>
				<p:commandButton id="btn_cancel" action="#{loginController.toProfile}" immediate="true" ajax="false" value="#{facesContext.translate('button.cancel')}" />
				<p:commandButton id="btn_ok" action="#{loginController.doChangePassword}" ajax="false" value="#{facesContext.translate('button.changepassword')}" />
			</ship:buttongroup>
		</ui:define>
		<ui:define name="help_de">
			TODO StS: Das Passwort muss zweimal eingegeben werden, um Tippfehler zu vermeiden. Es wird verschlüsselt in der Datenbank gespeichert und kann nicht mehr entschlüsselt werden. 
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/profile.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
	<ui:composition template="/pages/pridiatemplate.xhtml">
		<ui:define name="body">
			<p:panel header="#{facesContext.translate('title.profile.config')}">
				<p:panelGrid columns="2">
					<c:forEach items="#{profile.config}" var="p" varStatus="state">
						<h:outputText value="#{p.getTranslation(lang.simpleLocaleCode)}" />
						<ui:fragment rendered="#{!p.adminOnly or profile.hasPrivilege('admin')}">
							<p:inputText id="inputnumber_#{state.index}" value="#{p.value}" rendered="#{p.isNumber}">
								<f:convertNumber />
							</p:inputText>
							<p:inputText id="inputstring_#{state.index}" value="#{p.value}" rendered="#{p.isText}" />
							<p:colorPicker id="inputcolor_#{state.index}" value="#{p.value}" rendered="#{p.isColor}" />
							<h:outputText value="#{p.value}" rendered="#{!p.isNumber and !p.isText and !p.isColor}" />
              <ship:buttongroup>
                <p:commandButton id="btn_ok_#{state.index}" action="#{loginController.doSetConfigParam(p.key)}" ajax="false" value="#{facesContext.translate('button.approve')}" />
                <p:commandButton id="btn_cancel_#{state.index}" action="#{loginController.doUnsetConfigParam(p.key)}" ajax="false" value="#{facesContext.translate('button.remove')}" />
              </ship:buttongroup>
						</ui:fragment>
            <ui:fragment rendered="#{p.adminOnly and not profile.hasPrivilege('admin')}">
              <h:outputText value="#{p.value}" /><h:outputText value="*" style="color: red" title="only changeable by an admin" />
            </ui:fragment>
					</c:forEach>
				</p:panelGrid>
			</p:panel>
		</ui:define>
		<ui:define name="formbuttons">
			<p:commandButton id="btn_pwd" action="#{loginController.toPassword}" value="#{facesContext.translate('button.changepassword')}" ajax="false" rendered="#{!profile.hasKeycloakAccessToken()}" />
			<h:outputText value="keycloak login" rendered="#{profile.hasKeycloakAccessToken()}" />
		</ui:define>
		<ui:define name="help_de">
			TODO StS: Hier vorgenommene Einstellungen verändern die persönliche Sicht auf die Anwendung. 
		</ui:define>
	</ui:composition>
</h:body>
</html>