src/main/java/square2/modules/model/report/CalculationResultFileBean.java
package square2.modules.model.report;

import java.io.Serializable;

/**
 * 
 * @author henkej
 *
 */
public class CalculationResultFileBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private String name;
	private String fileContent;
	private String mimetype;

	/**
	 * get the size of file content
	 * 
	 * @return the size
	 */
	public Integer getSize() {
		return fileContent == null ? 0 : fileContent.length();
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *          the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the fileContent
	 */
	public String getFileContent() {
		return fileContent;
	}

	/**
	 * @param fileContent
	 *          the fileContent to set
	 */
	public void setFileContent(String fileContent) {
		this.fileContent = fileContent;
	}

	/**
	 * @return the mimetype
	 */
	public String getMimetype() {
		return mimetype;
	}

	/**
	 * @param mimetype
	 *          the mimetype to set
	 */
	public void setMimetype(String mimetype) {
		this.mimetype = mimetype;
	}
}

src/main/java/square2/modules/model/report/EditReportBean.java
package square2.modules.model.report;

import java.util.ArrayList;
import java.util.List;

import square2.modules.model.report.design.SnippletBean;

/**
 * 
 * @author henkej
 *
 */
public class EditReportBean extends NamedReportBean {
  private static final long serialVersionUID = 1L;

  private final Integer numberOfSelected;
  private final Integer numberOfTotal;
  private Integer offset;
  private Integer pageLength;

  /**
   * @param bean the report bean
   * @param functionlistName the function list name
   * @param variablegroupName the variable group name
   * @param snipplets the snipplets
   * @param pageLength length of a snipplets page
   * @param offset position of snipplet for the page
   * @param numberOfSelected number of selected variables in the variable group
   * @param numberOfTotal number of total variables in the variable group
   */
  public EditReportBean(ReportBean bean, String functionlistName, String variablegroupName,
      List<SnippletBean> snipplets, Integer pageLength, Integer offset, Integer numberOfSelected,
      Integer numberOfTotal) {
    super(bean, functionlistName, variablegroupName, snipplets);
    this.offset = offset == null ? 1 : offset;
    this.pageLength = pageLength == null ? 8 : pageLength;
    this.numberOfSelected = numberOfSelected;
    this.numberOfTotal = numberOfTotal;
  }

  /**
   * @return the number of selected variables
   */
  public Integer getNumberOfSelected() {
    return numberOfSelected;
  }

  /**
   * @return number of total variables
   */
  public Integer getNumberOfTotal() {
    return numberOfTotal;
  }

  private Integer getSnippletSize() {
    return getSnipplets().getRowCount();
  }

  /**
   * get the list of snipplets of the current page
   * 
   * @return list of snipplets
   */
  public List<SnippletBean> getPageSnipplets() {
    List<SnippletBean> list = new ArrayList<>();
    Integer lowerBorder = offset;
    Integer upperBorder = offset + pageLength;
    for (SnippletBean bean : getSnipplets()) {
      Integer orderNr = bean.getOrderNr();
      if ((lowerBorder <= orderNr) && (upperBorder > orderNr)) {
        list.add(bean);
      }
    }
    list.sort((o1, o2) -> o1 == null || o2 == null ? 0 : o1.compareTo(o2));
    return list;
  }

  /**
   * set the page by setting the offset
   * 
   * @param page the page
   */
  public void setPage(Integer page) {
    this.offset = page * pageLength;
  }

  /**
   * set the lastpage
   */
  public void setLastPage() {
    Integer snippletSize = getSnippletSize();
    Integer pages = snippletSize / pageLength;
    if (snippletSize % pageLength > 0) {
      pages++;
    }
    this.offset = (pages - 1) * pageLength;
  }

  /**
   * check if this is the current page
   * 
   * @param page the page
   * @return true or false
   */
  public Boolean isCurrentPage(Integer page) {
    return (page * pageLength) == this.offset;
  }

  /**
   * get the list of pages
   * 
   * @return list of pages; an empty list at least
   */
  public List<Integer> getPages() {
    List<Integer> list = new ArrayList<>();
    if (getHasPaginator()) {
      Integer pages = getSnippletSize() / pageLength;
      if (getSnippletSize() % pageLength > 0) {
        pages++;
      }
      for (int i = 0; i < pages; i++) {
        list.add(i);
      }
    }
    return list;
  }

  /**
   * determine of the snipplets have a paginator
   * 
   * @return true or false
   */
  public Boolean getHasPaginator() {
    return pageLength == null || offset == null || pageLength < getSnippletSize();
  }

  /**
   * @return the pageLength
   */
  public Integer getPageLength() {
    return pageLength;
  }
}

src/main/java/square2/modules/model/report/EnumShowNames.java
package square2.modules.model.report;

/**
 * 
 * @author henkej
 *
 */
public enum EnumShowNames {
	/**
	 * the function list name
	 */
	FUNCTIONLISTNAME,
	/**
	 * the variablegroup name
	 */
	VARIABLEGROUPNAME;
}

src/main/java/square2/modules/model/report/FunctionSelectionBean.java
package square2.modules.model.report;

import java.io.Serializable;

/**
 * 
 * @author henkej
 *
 */
public class FunctionSelectionBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private final Integer pk;
	private final String name;

	/**
	 * @param pk the id of the function selection
	 * @param name the name of the function selection
	 */
	public FunctionSelectionBean(Integer pk, String name) {
		super();
		this.pk = pk;
		this.name = name;
	}

	/**
	 * @return the pk
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
}

src/main/java/square2/modules/model/report/JsonMatrixContainerBean.java
package square2.modules.model.report;

import java.io.Serializable;

/**
 * 
 * @author henkej
 *
 */
public class JsonMatrixContainerBean implements Serializable {
  private static final long serialVersionUID = 1L;

  private final String jsonMatrix;

  /**
   * @param jsonMatrix the jsonMatrix string
   */
  public JsonMatrixContainerBean(String jsonMatrix) {
    super();
    this.jsonMatrix = jsonMatrix;
  }

  /**
   * @return the jsonMatrix
   */
  public String getJsonMatrix() {
    return jsonMatrix;
  }
}

src/main/java/square2/modules/model/report/MarkdownDownloadBean.java
package square2.modules.model.report;

import java.io.Serializable;

/**
 * 
 * @author henkej
 *
 */
public class MarkdownDownloadBean implements Serializable {
  private static final long serialVersionUID = 1L;
  private Integer fkReport;
  private SquareReportRendererFormatBean format;
  private Boolean debug;
  private Boolean filePath;
  private Boolean showErrors;

  /**
   * :)
   */
  public MarkdownDownloadBean() {
    super();
  }

  /**
   * @param fkReport the id of the report
   * @param format the format of the output
   * @param debug if debug is on
   * @param dontsave if the result is not saved
   * @param showErrors if errors should be rendered
   */
  public MarkdownDownloadBean(Integer fkReport, SquareReportRendererFormatBean format, Boolean debug, Boolean dontsave,
      Boolean showErrors) {
    this.fkReport = fkReport;
    this.format = format;
    this.debug = debug;
    this.filePath = dontsave;
    this.showErrors = showErrors;
  }

  /**
   * @return the fkReport
   */
  public Integer getFkReport() {
    return fkReport;
  }

  /**
   * @param fkReport the fkReport to set
   */
  public void setFkReport(Integer fkReport) {
    this.fkReport = fkReport;
  }

  /**
   * @return the json representation of the format bean
   */
  public String getFormatJson() {
  	return format == null ? "[]" : format.toJson();
  }
  
  /**
   * @param json the json representation of the format
   */
  public void setFormatJson(String json) {
  	format = json == null || json.isEmpty() ? null : new SquareReportRendererFormatBean(null, null, null, null).fromJson(json);
  }
  
  /**
   * @return the format
   */
  public SquareReportRendererFormatBean getFormat() {
    return format;
  }

  /**
   * @param format the format to set
   */
  public void setFormat(SquareReportRendererFormatBean format) {
    this.format = format;
  }

  /**
   * @return the debug
   */
  public Boolean getDebug() {
    return debug;
  }

  /**
   * @param debug the debug to set
   */
  public void setDebug(Boolean debug) {
    this.debug = debug;
  }

  /**
   * @return the dontsave
   */
  public Boolean getFilePath() {
    return filePath;
  }

  /**
   * @param filePath the dontsave to set
   */
  public void setFilePath(Boolean filePath) {
    this.filePath = filePath;
  }

  /**
   * @return the showErrors
   */
  public Boolean getShowErrors() {
    return showErrors;
  }

  /**
   * @param showErrors the showErrors to set
   */
  public void setShowErrors(Boolean showErrors) {
    this.showErrors = showErrors;
  }
}

src/main/java/square2/modules/model/report/ReportBean.java
package square2.modules.model.report;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.google.gson.Gson;

import square2.converter.Selectable;
import square2.modules.model.datamanagement.ReleaseBean;
import square2.modules.model.report.design.ReportPeriodBean;

/**
 * 
 * @author henkej
 *
 */
public class ReportBean implements Serializable, Comparable<ReportBean>, Selectable<ReportBean> {
	private static final long serialVersionUID = 1L;

	private final Integer pk;
	private String name;
	private String description;
	private Integer fkParent;
	private Integer fkLatexdef;
	private Integer fkFunctionlist;
	private Integer fkVariablegroupdef;
	private String vargroupname;
	private Date started;
	private Date stopped;
	private String runlog;
	private String runsum;
	private String latexcode;
	private Date lastchange;
	private List<ReleaseBean> releases;
	private List<ReportPeriodBean> intervals;

	/**
	 * @param pk
	 *          the id of the report
	 */
	public ReportBean(Integer pk) {
		this.pk = pk;
		this.releases = new ArrayList<>();
		this.intervals = new ArrayList<>();
	}
	
	@Override
	public String toJson() {
		return new Gson().toJson(this);
	}

	@Override
	public ReportBean fromJson(String json) {
		return new Gson().fromJson(json, ReportBean.class);
	}

	@Override
	public int compareTo(ReportBean o) {
		return o == null || name == null ? 0 : name.compareTo(o.getName());
	}

	@Override
	public String toString() {
		StringBuilder buf = new StringBuilder();
		buf.append("ReportBean@{pk=").append(pk);
		buf.append(", name=").append(name);
		buf.append(", description=").append(description);
		buf.append(", fkParent=").append(fkParent);
		buf.append(", fkLatexdef=").append(fkLatexdef);
		buf.append(", fkFunctionlist=").append(fkFunctionlist);
		buf.append(", fkVariablegroupdef=").append(fkVariablegroupdef);
		buf.append(", started=").append(started);
		buf.append(", stopped=").append(stopped);
		buf.append(", runlog=").append(runlog);
		buf.append(", runsum=").append(runsum);
		buf.append(", latexcode=").append(latexcode);
		buf.append(", lastchange=").append(lastchange);
		buf.append(", releases=").append(releases);
		buf.append(", intervals=").append(intervals).append("}");
		return buf.toString();
	}

	/**
	 * add the release bean to the list of releases
	 * 
	 * @param bean the release bean
	 */
  public void addRelease(ReleaseBean bean) {
    if (releases == null) {
      releases = new ArrayList<>();
    }
    releases.add(bean);
  }

	/**
	 * check if the report is being calculated currently
	 * 
	 * @return true or false
	 */
	public boolean getIsRunning() {
		return this.started != null && this.stopped == null;
	}

	/**
	 * tell me if this report has releases
	 * 
	 * @return true or false
	 */
	public boolean getHasNoReleases() {
		return this.releases == null || this.releases.isEmpty();
	}

	/**
	 * @return the pk
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *          the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *          the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the fkParent
	 */
	public Integer getFkParent() {
		return fkParent;
	}

	/**
	 * @param fkParent
	 *          the fkParent to set
	 */
	public void setFkParent(Integer fkParent) {
		this.fkParent = fkParent;
	}

	/**
	 * @return the fkLatexdef
	 */
	public Integer getFkLatexdef() {
		return fkLatexdef;
	}

	/**
	 * @param fkLatexdef
	 *          the fkLatexdef to set
	 */
	public void setFkLatexdef(Integer fkLatexdef) {
		this.fkLatexdef = fkLatexdef;
	}

	/**
	 * @return the fkFunctionlist
	 */
	public Integer getFkFunctionlist() {
		return fkFunctionlist;
	}

	/**
	 * @param fkFunctionlist
	 *          the functionlist to set
	 */
	public void setFkFunctionlist(Integer fkFunctionlist) {
		this.fkFunctionlist = fkFunctionlist;
	}

	/**
	 * @return the fkVariablegroupdef
	 */
	public Integer getFkVariablegroupdef() {
		return fkVariablegroupdef;
	}

	/**
	 * @param fkVariablegroupdef
	 *          the fkVariablegroupdef to set
	 */
	public void setFkVariablegroupdef(Integer fkVariablegroupdef) {
		this.fkVariablegroupdef = fkVariablegroupdef;
	}

	/**
	 * @return the started
	 */
	public Date getStarted() {
		return started;
	}

	/**
	 * @param started
	 *          the started to set
	 */
	public void setStarted(Date started) {
		this.started = started;
	}

	/**
	 * @return the stopped
	 */
	public Date getStopped() {
		return stopped;
	}

	/**
	 * @param stopped
	 *          the stopped to set
	 */
	public void setStopped(Date stopped) {
		this.stopped = stopped;
	}

	/**
	 * @return the runlog
	 */
	public String getRunlog() {
		return runlog;
	}

	/**
	 * @param runlog
	 *          the runlog to set
	 */
	public void setRunlog(String runlog) {
		this.runlog = runlog;
	}

	/**
	 * @return the runsum
	 */
	public String getRunsum() {
		return runsum;
	}

	/**
	 * @param runsum
	 *          the runsum to set
	 */
	public void setRunsum(String runsum) {
		this.runsum = runsum;
	}

	/**
	 * @return the latexcode
	 */
	public String getLatexcode() {
		return latexcode;
	}

	/**
	 * @param latexcode
	 *          the latexcode to set
	 */
	public void setLatexcode(String latexcode) {
		this.latexcode = latexcode;
	}

	/**
	 * @return the lastchange
	 */
	public Date getLastchange() {
		return lastchange;
	}

	/**
	 * @param lastchange
	 *          the lastchange to set
	 */
	public void setLastchange(Date lastchange) {
		this.lastchange = lastchange;
	}

	/**
	 * @return the releases
	 */
	public List<ReleaseBean> getReleases() {
		return releases;
	}

	/**
	 * @return the intervals
	 */
	public List<ReportPeriodBean> getIntervals() {
		return intervals;
	}

	/**
	 * @return the vargroupname
	 */
	public String getVargroupname() {
		return vargroupname;
	}

	/**
	 * @param vargroupname the vargroupname to set
	 */
	public void setVargroupname(String vargroupname) {
		this.vargroupname = vargroupname;
	}
}

src/main/java/square2/modules/model/report/ReportStatsBean.java
package square2.modules.model.report;

import java.text.FieldPosition;
import java.text.NumberFormat;
import java.text.ParsePosition;

/**
 * 
 * @author henkej
 *
 */
public class ReportStatsBean {
	private final Integer reportId;
	private final Double progress;
	private final String message;
	private final Boolean cancelled;

	/**
	 * @param reportId the report id
	 * @param progress the progress
	 * @param message the message
	 * @param cancelled the cancelled
	 */
	public ReportStatsBean(Integer reportId, Double progress, String message, Boolean cancelled) {
		super();
		this.reportId = reportId;
		this.progress = progress;
		this.message = message;
		this.cancelled = cancelled;
	}

	/**
	 * @return the reportId as string
	 */
	public String getReportIdString() {
		return reportId == null ? "" : reportId.toString();
	}

	/**
	 * @return the progress as string
	 */
	public String getProgressString() {
		return progress == null ? "" : progress.toString();
	}
	
	/**
	 * @return the reportId
	 */
	public Integer getReportId() {
		return reportId;
	}

	/**
	 * @return the progress
	 */
	public Double getProgress() {
		return progress;
	}

	/**
	 * @return the message
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * @return the cancelled
	 */
	public Boolean getCancelled() {
		return cancelled;
	}
}

src/main/java/square2/modules/model/report/ajax/MatrixElementBean.java
package square2.modules.model.report.ajax;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

/**
 * 
 * @author henkej
 *
 */
public class MatrixElementBean implements Serializable {
  private static final long serialVersionUID = 1L;
  private final Boolean selected;
  private final Map<String, ParamBean> params;

  /**
   * @param selected the selected
   */
  public MatrixElementBean(Boolean selected) {
    super();
    this.selected = selected;
    params = new HashMap<>();
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(this.getClass().getSimpleName());
    buf.append("@{selected=").append(selected);
    buf.append(",params=").append(params);
    buf.append("}");
    return buf.toString();
  }

  /**
   * @return the selected
   */
  public Boolean getSelected() {
    return selected;
  }

  /**
   * @return the params
   */
  public Map<String, ParamBean> getParams() {
    return params;
  }
}

src/main/webapp/pages/report/show.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship" xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
	<ui:composition template="/pages/pridiatemplate.xhtml">
		<ui:define name="body">
			<p:panel header="#{reportModel.showReportBean.name}" toggleable="true">
				<p:panelGrid columns="2" layout="grid">
					<h:outputText value="#{facesContext.translate('label.report.id')}" />
					<h:outputText value="#{reportModel.showReportBean.pk}" />
					<h:outputText value="#{facesContext.translate('label.report.name')}" />
					<h:outputText value="#{reportModel.showReportBean.name}" />
					<h:outputText value="#{facesContext.translate('label.report.description')}" />
					<h:outputText value="#{reportModel.showReportBean.description}" />
					<h:outputText value="#{facesContext.translate('label.report.analysistemplate')}" />
					<h:outputText value="#{reportModel.showReportBean.functionlistName}" />
					<h:outputText value="#{facesContext.translate('label.analysis.matrix.variablegroup')}" />
					<h:outputText value="#{reportModel.showReportBean.variablegroupName}" />
					<h:outputText value="#{facesContext.translate('label.report.generate.started')}" />
					<h:outputText value="#{reportModel.showReportBean.started}">
						<f:convertDateTime pattern="dd.MM.yyyy HH:mm:ss" />
					</h:outputText>
					<h:outputText value="#{facesContext.translate('label.report.generate.stopped')}" />
					<h:outputText value="#{reportModel.showReportBean.stopped}">
						<f:convertDateTime pattern="dd.MM.yyyy HH:mm:ss" />
					</h:outputText>
					<h:outputText value="#{facesContext.translate('label.report.generate.releases')}" />
					<h:dataTable value="#{reportModel.showReportBean.releases}" var="rel"
						rendered="#{reportModel.showReportBean.releases != null}">
						<h:column>
							<h:outputText value="#{rel.name}" />
						</h:column>
					</h:dataTable>
					<h:outputText value="#{facesContext.translate('label.report.intervals')}" />
					<h:dataTable value="#{reportModel.showReportBean.intervals}" var="i"
						rendered="#{reportModel.showReportBean.intervals != null}">
						<h:column>
							<h:outputText value="#{i.string}" />
						</h:column>
					</h:dataTable>
					<h:outputText value="#{facesContext.translate('label.report.monitor.runtimestats')}"
						rendered="#{reportModel.showReportBean.stats != null}" />
					<p:panelGrid columns="4" rendered="#{reportModel.showReportBean.stats != null}">
						<h:outputText value="ID" />
						<h:outputText value="progress" />
						<h:outputText value="message" />
						<h:outputText value="cancelled" />
						<h:outputText value="#{reportModel.showReportBean.stats.reportIdString}" />
						<h:outputText value="#{reportModel.showReportBean.stats.progressString}" />
						<h:outputText value="#{reportModel.showReportBean.stats.message}" />
						<h:outputText value="#{reportModel.showReportBean.stats.cancelled}" />
					</p:panelGrid>
					<!-- TODO: replace by SquareControl2.call_results_exist() -->
					<h:outputText value="Results" rendered="#{reportModel.showReportBean.stopped != null}" />
					<p:link href="#{reportModel.getSquarevUrl(facesContext)}/SQuaReV/report/#{reportModel.showReportBean.pk}" target="#" onclick="ship.processingCloseable()"
						value="#{reportModel.showReportBean.name}" rendered="#{reportModel.showReportBean.stopped != null}" />
				</p:panelGrid>
				<h:panelGroup rendered="#{reportModel.showReportBean.stopped != null}">
					<!-- TODO: replace by SquareControl2.call_results_exist() -->
					<h:outputText value="#{facesContext.translate('label.report.download.formats')}" />
					<p:selectBooleanCheckbox id="debug" value="#{reportModel.mdb.debug}"
						itemLabel="#{facesContext.translate('checkbox.debug')}" />
					<p:selectOneMenu id="format" value="#{reportModel.mdb.formatJson}" filter="true">
						<f:selectItems value="#{reportModel.formats}" var="f" itemValue="#{f.toJson()}" itemLabel="#{f.label}" />
					</p:selectOneMenu>
					<p:commandButton id="btn_markdown" action="#{reportController.doGenerateMarkdownResult}" icon="fa fa-play"
						value="#{facesContext.translate('button.generate')}" onclick="PF('modalrenderinfo').show()" ajax="false" />
					<p:commandButton id="btn_logfile" action="#{reportController.doLogFileDownload}" icon="fa fa-file-o"
						value="#{facesContext.translate('button.download.log.r')}" title="#{facesContext.translate('button.download.log')}"
						disabled="#{!profile.hasPrivilege('admin')}" ajax="false" />
					<p:commandButton id="btn_refresh" action="#{reportController.toShow(reportModel.showReportBean)}" icon="fa fa-refresh"
						value="#{facesContext.translate('button.reload')}" ajax="false" onclick="ship.processing()" oncomplete="ship.processed()" />
				</h:panelGroup>
			</p:panel>
			<p:dialog widgetVar="modalrenderinfo" id="modalrenderinfo" header="#{facesContext.translate('label.started.rendering')}">
				<p>
					<h:outputText value="#{facesContext.translate('text.started.rendering')}" />
				</p>
				<f:facet name="footer">
					<p:commandButton value="#{facesContext.translate('button.ok')}" onclick="PF('modalrenderinfo').hide();" type="button" />
				</f:facet>
			</p:dialog>
			<p:panel header="#{facesContext.translate('label.report.monitor.runtimestats')}" toggleable="true" collapsed="true"
				rendered="#{profile.hasPrivilege('statisticadmin')}">
				<p:dataTable id="performance" value="#{reportModel.performance}" var="p">
					<p:column headerText="#{facesContext.translate('label.calculation.perf.functionname')}">
						<h:outputText value="#{p.functionname}" />
					</p:column>
					<p:column headerText="#{facesContext.translate('label.calculation.perf.varmagnitude')}">
						<h:outputText value="#{p.varmagnitude}" />
					</p:column>
					<p:column headerText="#{facesContext.translate('label.calculation.perf.userself')}">
						<h:outputText value="#{p.userself}" />
					</p:column>
					<p:column headerText="#{facesContext.translate('label.calculation.perf.sysself')}">
						<h:outputText value="#{p.sysself}" />
					</p:column>
					<p:column headerText="#{facesContext.translate('label.calculation.perf.elapsed')}">
						<h:outputText value="#{p.elapsed}" />
					</p:column>
					<p:column headerText="#{facesContext.translate('label.calculation.perf.userchild')}">
						<h:outputText value="#{p.userchild}" />
					</p:column>
					<p:column headerText="#{facesContext.translate('label.calculation.perf.syschild')}">
						<h:outputText value="#{p.syschild}" />
					</p:column>
				</p:dataTable>
			</p:panel>
			<p:panel header="#{facesContext.translate('label.calculation.result.download')}" toggleable="true" collapsed="true"
				rendered="#{profile.hasPrivilege('statisticadmin')}">
				<p:dataTable id="results" value="#{reportModel.calculationResults}" var="crf">
					<p:column headerText="#{facesContext.translate('label.calculation.result.download')}">
						<p:commandLink id="btn_downloadfile" action="#{reportController.doDownloadFile(crf)}" value="#{crf.name}" ajax="false" />
					</p:column>
					<p:column headerText="#{facesContext.translate('label.calculation.result.size')}">
						<h:outputText value="#{crf.size}" />
					</p:column>
				</p:dataTable>
			</p:panel>
		</ui:define>
		<ui:define name="formbuttons">
			<p:commandButton id="btn_abort" action="#{reportController.toWelcome}" value="#{facesContext.translate('button.overview')}"
				immediate="true" ajax="false" />
			<p:commandButton id="btn_edit" action="#{reportController.toEdit(reportModel.showReportBean)}"
				value="#{facesContext.translate('button.edit.definition')}" immediate="true" ajax="false"
				rendered="#{profile.hasPrivilege('reportwriter')}" />
			<p:commandButton id="btn_configure" action="#{reportController.toConfigure(reportModel.showReportBean)}"
				value="#{facesContext.translate('button.edit.report.configure')}" immediate="true" ajax="false"
				rendered="#{profile.hasPrivilege('reportwriter')}" />
			<p:commandButton id="btn_show" action="#{reportController.toCalculate(reportModel.showReportBean)}"
				value="#{facesContext.translate('button.calculate')}" immediate="true" ajax="false"
				rendered="#{profile.hasPrivilege('reportbuilder')}" />
			<p:commandButton id="btn_properties" action="#{reportController.toProperties(reportModel.showReportBean)}"
				value="#{facesContext.translate('button.edit.report.properties')}" immediate="true" ajax="false" />
		</ui:define>
	</ui:composition>
</h:body>
</html>