src/main/java/square2/modules/model/admin/ImpressumBean.java
package square2.modules.model.admin;

import java.util.Locale;

import de.ship.dbppsquare.square.enums.EnumIsocode;

/**
 * 
 * @author henkej
 *
 */
public class ImpressumBean {
	private final Locale locale;
	private final String isocode;
	private String content;

	/**
	 * @param isocodeEnum
	 *          isocode enum of this translation
	 * @param content
	 *          the translation
	 */
	public ImpressumBean(EnumIsocode isocodeEnum, String content) {
		super();
		this.isocode = isocodeEnum == null ? "" : (isocodeEnum.getLiteral() == null ? "" : isocodeEnum.getLiteral());
		this.locale = Locale.forLanguageTag(isocode.toLowerCase().replaceAll("\\_", "-"));
		this.content = content == null ? "" : content;
	}

	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}

	/**
	 * @param content
	 *          the content
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * @return the locale
	 */
	public Locale getLocale() {
		return locale;
	}

	/**
	 * @return the isocode
	 */
	public String getIsocode() {
		return isocode;
	}
}

src/main/java/square2/modules/model/admin/UserBean.java
package square2.modules.model.admin;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * @author henkej
 * 
 */
public class UserBean implements Serializable, Comparable<UserBean> {
	private static final long serialVersionUID = 1L;
	private String forename;
	private String surname;
	private String username;
	private Integer usnr;
	private Date expire;

	public String toString() {
		StringBuilder buf = new StringBuilder();
		buf.append(forename).append(" ").append(surname);
		buf.append(" (").append(username).append(", ");
		buf.append(usnr).append(")");
		buf.append(expire);
		return buf.toString();
	}

	@Override
	public int compareTo(UserBean o) {
		String sortname = getSortname();
		return o == null ? 0 : sortname.compareTo(o.getSortname());
	}

	/**
	 * @return true if expire is before the current date
	 */
	public Boolean getIsExpired() {
		return expire == null ? null : expire.before(new Date());
	}

	private String getSortname() {
		return new StringBuilder().append(surname).append(forename).toString().toLowerCase();
	}

	/**
	 * get the full name of the user
	 * 
	 * @return the full name
	 */
	public String getFullname() {
		return new StringBuilder().append(forename).append(" ").append(surname).toString();
	}

	/**
	 * @return the forename
	 */
	public String getForename() {
		return forename;
	}

	/**
	 * @param forename
	 *          the forename to set
	 */
	public void setForename(String forename) {
		this.forename = forename;
	}

	/**
	 * @return the surname
	 */
	public String getSurname() {
		return surname;
	}

	/**
	 * @param surname
	 *          the surname to set
	 */
	public void setSurname(String surname) {
		this.surname = surname;
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username
	 *          the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the usnr
	 */
	public Integer getUsnr() {
		return usnr;
	}

	/**
	 * @param usnr
	 *          the usnr to set
	 */
	public void setUsnr(Integer usnr) {
		this.usnr = usnr;
	}

	/**
	 * @return the expire
	 */
	public Date getExpire() {
		return expire;
	}

	/**
	 * @param expire
	 *          the expire to set
	 */
	public void setExpire(Date expire) {
		this.expire = expire;
	}
}

src/main/java/square2/modules/model/admin/UsergroupBean.java
package square2.modules.model.admin;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import square2.modules.model.ProfileBean;

/**
 * 
 * @author henkej
 *
 */
public class UsergroupBean implements Serializable, Comparable<UsergroupBean> {
	private static final long serialVersionUID = 1L;

	private final Integer pk;
	private String name;
	private List<ProfileBean> users;

	/**
	 * create a new user group bean
	 * 
	 * @param pk
	 *          the id of the user group
	 * @param name
	 *          the name of the group bean
	 * @param users
	 *          the list of users
	 */
	public UsergroupBean(Integer pk, String name, List<ProfileBean> users) {
		super();
		this.pk = pk;
		this.name = name;
		this.users = new ArrayList<>();
		if (users != null) {
			this.users.addAll(users);
		}
	}

	@Override
	public int compareTo(UsergroupBean o) {
		return name == null || o == null || o.getName() == null ? 0 : name.compareTo(o.getName());
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *          the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the pk
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * @return the users
	 */
	public List<ProfileBean> getUsers() {
		return users;
	}
}

src/main/java/square2/modules/model/statistic/FunctionInputBean.java
package square2.modules.model.statistic;

import java.io.Serializable;

/**
 * 
 * @author henkej
 * 
 */
public class FunctionInputBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private final Integer pk;
	private String name;
	private String standard;
	private String description;
	private FunctioninputtypeBean fkType;

	/**
	 * @param pk
	 *          the id
	 */
	public FunctionInputBean(Integer pk) {
		super();
		this.pk = pk;
	}

	@Override
	public String toString() {
		StringBuilder buf = new StringBuilder(this.getClass().getSimpleName());
		buf.append("@{pk=").append(pk);
	  buf.append(", name=").append(name);
		buf.append(", standard=").append(standard);
		buf.append(", description=").append(description);
		buf.append(", fkType=").append(fkType);
		buf.append("}");
		return buf.toString();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		FunctionInputBean other = (FunctionInputBean) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *          the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the standard
	 */
	public String getStandard() {
		return standard;
	}

	/**
	 * @param standard
	 *          the standard to set
	 */
	public void setStandard(String standard) {
		this.standard = standard;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *          the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the fkType
	 */
	public FunctioninputtypeBean getFkType() {
		return fkType;
	}

	/**
	 * @param fkType
	 *          the fkType to set
	 */
	public void setFkType(FunctioninputtypeBean fkType) {
		this.fkType = fkType;
	}

	/**
	 * @return the pk
	 */
	public Integer getPk() {
		return pk;
	}
}

src/main/java/square2/modules/model/statistic/FunctionOutputBean.java
package square2.modules.model.statistic;

import java.io.Serializable;

/**
 * 
 * @author henkej
 * 
 */
public class FunctionOutputBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private final Integer id;
	private String name;
	private String description;
	private Integer usage;

	/**
	 * create new function output bean
	 * 
	 * @param id
	 *          the id
	 */
	public FunctionOutputBean(Integer id) {
		this.id = id;
	}

	@Override
	public String toString() {
		StringBuilder buf = new StringBuilder(this.getClass().getSimpleName());
		buf.append("@{id=").append(id);
		buf.append(",name=").append(name);
		buf.append(",description=").append(description);
		buf.append(",usage=").append(usage);
		buf.append("}");
		return buf.toString();
	}

	/**
	 * @return the usage label
	 */
	public String getUsageLabel() {
		return new StringBuilder("label.statistic.outputusage.").append(usage).toString();
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *          the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *          the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the usage
	 */
	public Integer getUsage() {
		return usage;
	}

	/**
	 * @param usage
	 *          the usage to set
	 */
	public void setUsage(Integer usage) {
		this.usage = usage;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}
}

src/main/java/square2/modules/model/template/report/FunctionoutputBean.java
package square2.modules.model.template.report;

import java.io.Serializable;

/**
 * 
 * @author henkej
 *
 */
public class FunctionoutputBean implements Serializable, Comparable<FunctionoutputBean> {
	private static final long serialVersionUID = 1L;

	private final Integer fkFunctionoutput;
	private final String name;
	
	/**
	 * @param fkFunctionoutput the id of the function output
	 * @param name the name of the function output
	 */
	public FunctionoutputBean(Integer fkFunctionoutput, String name) {
		this.fkFunctionoutput = fkFunctionoutput;
		this.name = name;
	}

  @Override
  public int compareTo(FunctionoutputBean bean) {
    return bean == null || name == null || bean.getName() == null ? 0 : name.compareTo(bean.getName());
  }

  /**
	 * @return the fkFunctionoutput
	 */
	public Integer getFkFunctionoutput() {
		return fkFunctionoutput;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
}

src/main/java/square2/modules/control/ImpressumController.java
package square2.modules.control;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

import square2.help.SquareFacesContext;
import square2.modules.control.help.Pages;

/**
 * 
 * @author henkej
 *
 */
@Named
@RequestScoped
public class ImpressumController extends NavigationController {
	/**
	 * go to impressum page
	 * 
	 * @param facesContext
	 *          the context of this function call
	 * 
	 * @return navigation destination
	 */
	public String toImpressum(SquareFacesContext facesContext) {
		return navigateTo(facesContext, Pages.IMPRESSUM);
	}

	@Override
	public boolean getIsCurrentController() {
		return false;
	}
}

src/main/java/square2/modules/control/LoginController.java
package square2.modules.control;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import square2.help.ThemeBean;
import square2.modules.control.help.Pages;
import square2.modules.model.ApplicationBean;
import square2.modules.model.LoginModel;

/**
 * 
 * @author henkej
 * 
 */
@Named
@RequestScoped
public class LoginController extends NavigationController {
	@Inject
	@Named(value = "loginModel")
	private LoginModel model;

	@Inject
	@Named(value = "applicationBean")
	private ApplicationBean applicationBean;

	@Inject
	@Named(value = "themeBean")
	private ThemeBean themeBean;

	/**
	 * create new login controller
	 */
	public LoginController() {
		super(Pages.PROFILE, Pages.LOGIN, Pages.MAIN);
	}

	/**
	 * load maintenance information
	 * 
	 * @return navigation destination
	 */
	public String toLogin() {
		return navigateTo(getFacesContext(), Pages.LOGIN);
	}

	/**
	 * check username and password and navigate to internal page if correct
	 * 
	 * @return navigation destination
	 */
	public String doLogin() {
		boolean result = model.doLogin(getFacesContext(), applicationBean);
		return result ? navigateTo(getFacesContext(), Pages.MAIN) : toLogin();
	}

	/**
	 * clear session and go to login page
	 * 
	 * @return navigation destination
	 */
	public String doLogout() {
		model.doLogout(getFacesContext(), applicationBean);
		return toLogin();
	}

	/**
	 * nagivate to change password
	 * 
	 * @return navigation destination
	 */
	public String toPassword() {
		model.toChangePassword(getFacesContext());
		return navigateTo(getFacesContext(), Pages.PASSWORD);
	}

	/**
	 * nagivate to change password
	 * 
	 * @return navigation destination
	 */
	public String toProfile() {
		model.toChangePassword(getFacesContext());
		return navigateTo(getFacesContext(), Pages.PROFILE);
	}

	/**
	 * change password
	 * 
	 * @return navigation destination
	 */
	public String doChangePassword() {
		model.changePassword(getFacesContext());
		return navigateTo(getFacesContext(), Pages.PROFILE);
	}

	/**
	 * set configuration param
	 * 
	 * @param key
	 *          the key
	 * @return navigation destination
	 */
	public String doSetConfigParam(String key) {
		model.setConfigParam(getFacesContext(), key, getFacesContext().getUsnr(), getFacesContext().getProfile().getConfig(key), themeBean);
		model.setConfigValue(null); // for next changes, free variable
		return toProfile();
	}

	/**
	 * unset configuration param
	 * 
	 * @param key
	 *          the key
	 * @return navigation destination
	 */
	public String doUnsetConfigParam(String key) {
		model.setConfigParam(getFacesContext(), key, getFacesContext().getUsnr(), null, themeBean);
		return toProfile();
	}

	@Override
	public boolean getIsCurrentController() {
		return getIsCurrentController(getFacesContext());
	}
}

src/main/java/square2/modules/control/SubmenuController.java
package square2.modules.control;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.faces.context.FacesContext;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import square2.modules.control.help.Pages;
import square2.modules.control.help.Session;

/**
 * 
 * @author henkej
 *
 */
public abstract class SubmenuController extends UserRightController {
	private static final Logger LOGGER = LogManager.getLogger(SubmenuController.class);

	private Pages[] allowed;

	/**
	 * create new submenu controller
	 * 
	 * @param mainPage
	 *          the main page
	 * @param pages
	 *          the valid pages
	 */
	public SubmenuController(Pages mainPage, Pages... pages) {
		super(constructorHelper(mainPage, pages));
		this.allowed = pages;
	}

	private static final Pages[] constructorHelper(Pages mainPage, Pages... pages) {
		List<Pages> p = new ArrayList<>(Arrays.asList(pages));
		p.add(mainPage);
		Pages all[] = new Pages[p.size()];
		all = p.toArray(all);
		return all;
	}

	/**
	 * call getIsCurrentSubController with current facesContext
	 * 
	 * @return true or false
	 */
	public abstract boolean getIsCurrentSubController();

	/**
	 * check if this is the current sub controller
	 * 
	 * @param facesContext
	 *          the context of this function call
	 * @return true or false
	 */
	public boolean getIsCurrentSubController(FacesContext facesContext) {
		Pages page = (Pages) facesContext.getExternalContext().getSessionMap().get(Session.SUBPAGE.get());
		for (Pages p : allowed) {
			if (p.equals(page)) {
				return true;
			}
		}
		return false;
	}

	/**
	 * get the active panel
	 * 
	 * @param facesContext
	 *          the context of this function call
	 * @return the active panel
	 */
	public String getActivePanel(FacesContext facesContext) {
		return (String) facesContext.getExternalContext().getSessionMap().get(Session.ACTIVE_PANEL.get());
	}

	/**
	 * set the active panel
	 * 
	 * @param activePanel
	 *          the active panel
	 * @param facesContext
	 *          the context of this function call
	 */
	public void setActivePanel(String activePanel, FacesContext facesContext) {
		facesContext.getExternalContext().getSessionMap().put(Session.ACTIVE_PANEL.get(), activePanel);
		LOGGER.debug("set active panel to {}", activePanel);
	}
}

src/main/webapp/pages/admin/fileupload.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship" xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
	<ui:composition template="/pages/pridiatemplate.xhtml">
		<ui:define name="location">
			<ui:include src="/pages/admin/submenu.xhtml" />
		</ui:define>
		<ui:define name="body">
			<p:panel header="#{facesContext.translate('title.admin.fileupload')}">
				<p:panelGrid columns="2">
					<h:inputFile id="file" value="#{adminModel.file}" />
					<p:commandButton id="btn_do" action="#{adminController.doFileUpload}" value="#{facesContext.translate('button.approve')}" ajax="false" />
				</p:panelGrid>
			</p:panel>
		</ui:define>
		<ui:define name="help_de">
			TODO StS: Mit diesem Dialog kann der Upload von Dateien getestet werden. Die hochgeladenen Daten werden nicht gespeichert. 
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/admin/impressum.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship" xmlns:p="http://primefaces.org/ui" xmlns:c="http://java.sun.com/jsp/jstl/core">
<h:head></h:head>
<h:body>
	<ui:composition template="/pages/pridiatemplate.xhtml">
		<ui:define name="location">
			<ui:include src="/pages/admin/submenu.xhtml" />
		</ui:define>
		<ui:define name="body">
			<p:panel header="#{facesContext.translate('title.impressum')}">
				<p:accordionPanel>
					<c:forEach items="#{adminModel.impressums}" var="i" varStatus="status">
						<p:tab id="#{i.locale}" title="#{i.locale.displayName}" titleStyleClass="accordionpanelheader">
							<p:inputTextarea id="input_#{status.index}" value="#{i.content}" style="width: 100%" rows="20" />
							<p:commandButton id="btn_#{status.index}" action="#{adminController.doUpdateImpressum(i)}" value="#{facesContext.translate('button.approve')}" ajax="false" />
						</p:tab>
					</c:forEach>
				</p:accordionPanel>
			</p:panel>
		</ui:define>
		<ui:define name="help_de">
			TODO StS: Das Impressum wird in jeder unterstützten Sprache dargestellt. Änderungen am Inhalt können durch den Button Übernehmen in der Datenbank gespeichert werden. Das Impressum ist durch jeden Nutzer in der aktuell eingestellten Sprache über die Menuleiste einsehbar. 
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/admin/users.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ship="http://xmlns.jcp.org/jsf/composite/ship" xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
	<ui:composition template="/pages/pridiatemplate.xhtml">
		<ui:define name="location">
			<ui:include src="/pages/admin/submenu.xhtml" />
		</ui:define>
		<ui:define name="body">
			<p:panel>
				<p:accordionPanel id="acc" activeIndex="3">
					<p:tab id="register" title="#{facesContext.translate('title.admin.users.register')}" titleStyleClass="accordionpanelheader">
						<p:panelGrid columns="2">
							<h:outputText value="#{facesContext.translate('admin.table.right.username')}" />
							<p:inputText id="username" value="#{adminModel.userBean.username}" />
							<h:outputText value="#{facesContext.translate('admin.table.right.forename')}" />
							<p:inputText id="forename" value="#{adminModel.userBean.forename}" />
							<h:outputText value="#{facesContext.translate('admin.table.right.surname')}" />
							<p:inputText id="surname" value="#{adminModel.userBean.surname}" />
							<h:outputText value="" />
							<p:commandButton id="btn_adduser" action="#{adminController.doAddUser}" value="#{facesContext.translate('button.add')}" ajax="false" icon="fa fa-plus" />
						</p:panelGrid>
					</p:tab>
					<p:tab id="delete" title="#{facesContext.translate('title.admin.users.remove')}" titleStyleClass="accordionpanelheader">
						<p:panelGrid columns="3">
							<h:outputText value="#{facesContext.translate('label.name')}" />
							<p:selectOneMenu id="delusers" value="#{adminModel.usnrdel}" filter="true">
								<f:selectItem itemValue="" itemLabel="#{facesContext.translate('button.choose')}" />
								<f:selectItems value="#{adminModel.users}" var="u" itemValue="#{u.usnr}" itemLabel="#{u.fullname}" />
							</p:selectOneMenu>
							<ship:removeButton id="btn_deleteuser" action="#{adminController.doDeleteUser}" value="#{facesContext.translate('button.delete')}" isLink="false" title="#{facesContext.translate('title.delete.approve')}"
								tooltip="#{facesContext.translate('button.delete')}" approveButtonLabel="#{facesContext.translate('button.yes')}" cancelButtonLabel="#{facesContext.translate('button.no')}" iconbutton="false">
								<h:outputText value="#{facesContext.translate('button.approve')}" />
							</ship:removeButton>
						</p:panelGrid>
					</p:tab>
					<p:tab id="allow" title="#{facesContext.translate('title.admin.users.add')}" titleStyleClass="accordionpanelheader">
						<p:panelGrid columns="3">
							<h:outputText value="#{facesContext.translate('label.name')}" />
							<p:selectOneMenu id="addusers" value="#{adminModel.usnr}" filter="true">
								<f:selectItem itemValue="" itemLabel="#{facesContext.translate('button.choose')}" />
								<f:selectItems value="#{adminModel.users}" var="u" itemValue="#{u.usnr}" itemLabel="#{u.fullname}" />
							</p:selectOneMenu>
							<p:commandButton id="btn_createlogin" action="#{adminController.doCreateLogin}" value="#{facesContext.translate('button.add')}" ajax="false" icon="fa fa-plus" />
						</p:panelGrid>
					</p:tab>
					<p:tab id="list" title="#{facesContext.translate('title.admin.users.list')}" titleStyleClass="accordionpanelheader">
						<p:dataTable id="sq2users" value="#{adminModel.square2users}" var="s" lang="#{lang.simpleLocaleCode}" saveState="true">
							<p:column headerText="#{facesContext.translate('admin.table.right.username')}" filterable="true" sortable="true" filterBy="#{s.username}" sortBy="#{s.username}" filterMatchMode="contains"
							          styleClass="column-name">
								<h:outputText value="#{s.username}" styleClass="#{s.isExpired ? 'strikethroughred' : ''}" />
							</p:column>
							<p:column headerText="#{facesContext.translate('admin.table.right.forename')}" filterable="true" sortable="true" filterBy="#{s.forename}" sortBy="#{s.forename}" filterMatchMode="contains"
							          styleClass="column-description">
								<h:outputText value="#{s.forename}" styleClass="#{s.isExpired ? 'strikethroughred' : ''}" />
							</p:column>
							<p:column headerText="#{facesContext.translate('admin.table.right.surname')}" filterable="true" sortable="true" filterBy="#{s.surname}" sortBy="#{s.surname}" filterMatchMode="contains"
							          styleClass="column-description">
								<h:outputText value="#{s.surname}" styleClass="#{s.isExpired ? 'strikethroughred' : ''}" />
							</p:column>
							<p:column headerText="#{facesContext.translate('admin.table.user.expire')}" filterable="true" sortable="true" filterBy="#{s.expire}" sortBy="#{s.expire}" filterMatchMode="contains"
							          styleClass="column-datetime">
								<h:outputText value="#{s.expire}">
									<f:convertDateTime pattern="dd.MM.yyyy HH:mm" /> <!-- TODO: localize date format -->
								</h:outputText>
								<ui:fragment rendered="#{s.isExpired}">
									<i class="fa fa-exclamation-triangle" style="color: #aa0000; margin-left: 8px"></i>
								</ui:fragment>
							</p:column>
							<p:column headerText="#{facesContext.translate('admin.table.user.activity')}" filterable="true" sortable="true" filterBy="#{s.isExpired}" sortBy="#{s.isExpired}" filterMatchMode="contains"
							          styleClass="column-userstate">
								<h:outputText value="#{facesContext.translate(s.isExpired ? 'label.expired' : 'label.active')}" />
							</p:column>
							<p:column styleClass="twoiconbuttons">
								<ship:buttongroup>
									<p:menuButton id="btn_addtime" value="" icon="fa fa-clock-o" styleClass="iconbutton">
										<p:menuitem id="addoneyear" action="#{adminController.doAddExpire(s.usnr, 365)}" ajax="false" value="#{facesContext.translate('label.admin.users.add1year')}" style="color: black !important" />
										<p:menuitem id="addsevendays" action="#{adminController.doAddExpire(s.usnr, 7)}" ajax="false" value="#{facesContext.translate('label.admin.users.add1week')}" style="color: black !important" />
										<p:menuitem id="setyesterday" action="#{adminController.doSetExpire(s.usnr, -1)}" ajax="false" value="#{facesContext.translate('label.admin.users.setyesterday')}" style="color: black !important" />
									</p:menuButton>
									<ship:removeButton id="btn_removeuser" action="#{adminController.doRemoveUser(s.usnr)}" value="" isLink="false" title="#{facesContext.translate('title.delete.approve')}"
										tooltip="#{facesContext.translate('button.delete')}" approveButtonLabel="#{facesContext.translate('button.yes')}" cancelButtonLabel="#{facesContext.translate('button.no')}">
										<h:outputText value="#{facesContext.translate('confirmation.delete', s.fullname)}" />
									</ship:removeButton>
								</ship:buttongroup>
							</p:column>
						</p:dataTable>
					</p:tab>
				</p:accordionPanel>
			</p:panel>
		</ui:define>
		<ui:define name="help_de">
			TODO StS: Auf dieser Seite werden die Anwendungsnutzer verwaltet. Nutzer können registriert werden, um im System vorgehalten zu werden. Registrierte Nutzer können für den Zugang zur Anwendung freigeschaltet werden. Nur nicht-registrierte Benutzer können entfernt werden. Wenn ein Nutzer aus der Liste der Webanwendungsnutzer gelöscht wird, wird damit nur sein Zugang zur Anwendung entfernt; er bleibt registriert.  
		</ui:define>
	</ui:composition>
</h:body>
</html>